---
title: An R Markdown document converted from "C:\Users\admin\Downloads\Paper-1-Poisson-Loglinear-Regression\Notebook
  1.ipynb"
output: html_document
---

```{r}
install.packages("readstata13")
install.packages("glmmTMB")
install.packages("jtools")
install.packages("kableExtra")
install.packages("DHARMa")
install.packages("performance")
install.packages("here")
```

```{r}
library(readstata13)
library(ggplot2)
library(dplyr)
library(jtools)
library(kableExtra)
library(MASS)
library(DHARMa)
library(glmmTMB)
library(performance)
library(here)
```

```{r}
here("PHIR71FL.DTA")
```

```{r}
dat <- read.dta13(here("PHIR71FL.DTA"))
```

```{r}
voi <- c("v004", "v005", "v613", "v012", "v107", "v190", "v301", "v136")
```

```{r}
#Removing incomplete cases
df <- dat[complete.cases(dat[,voi]), voi]
colnames(df) <- c("ultimate_area_unit","samp_weights","no_of_children", "age", "education", "wealth", "con_knowledge", "hhsize")
df$samp_weights <- df$samp_weights/1000000

```

### Poisson model

```{r}
fit1 <- glmmTMB(no_of_children ~ age + education + wealth + con_knowledge + hhsize + (1|ultimate_area_unit), data =df, family = poisson, weights = samp_weights)
```

### Model check only

```{r}
car::durbinWatsonTest(resid(fit1))
```

```{r}
check_overdispersion(fit1) #Thus, we will move onto an NB model
testDispersion(fit1)
```

```{r}
check_zeroinflation(fit1)
testZeroInflation(fit1)
```

```{r}
check_collinearity(fit1)
```

```{r}
check_heteroscedasticity(fit1)
```

```{r}
sum(check_outliers(fit1))
```

```{r}
check_model(fit1)
```

```{r}
model_performance(fit1)
```

### Negative binomial model

```{r}
nb.fit1 <- glmmTMB(no_of_children ~ age + education + wealth + con_knowledge + hhsize + (1|ultimate_area_unit), data =df, family = nbinom2, weights = samp_weights)
```

```{r}
summary(nb.fit1)
```

### Model check only

```{r}
car::durbinWatsonTest(resid(nb.fit1))
```

<!-- # ```{r} -->

<!-- # check_overdispersion(nb.fit1) #Thus, we will move onto an NB model -->

<!-- # testDispersion(nb.fit1) -->

<!-- # ``` -->

<!-- #  -->

<!-- # ```{r} -->

<!-- # check_zeroinflation(nb.fit1) -->

<!-- # testZeroInflation(nb.fit1) -->

<!-- # ``` -->

```{r}
check_collinearity(nb.fit1)
```

```{r}
sum(check_outliers(nb.fit1))
```

```{r}
check_model(nb.fit1)
```

```{r}
model_performance(nb.fit1)
```
